// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 加速器类型。当前仅 `Metal` / `Cpu` 生产使用；`None` 预留给 runtime
 * 初始化失败时的明确兜底（SPEC §3 `acceleratorKind`）。
 * 未来扩展 CUDA / Vulkan 必须走 SPEC §7 Ask First（feature flag whitelist）。
 */
export type AcceleratorKind = "metal" | "cpu" | "none";
