// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 策略层对命令的最终裁决。和执行器内的 AST 判定结果对齐，但留在 models 中供
 * audit / ts-rs / UI 状态复用。
 */
export type AiAllowlistDecision = "allow" | "require_confirm" | "deny";
