// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiStepKind } from "./AiStepKind";

/**
 * `ai:await_confirm` —— write/action step 等待用户确认执行。
 */
export type AiAwaitConfirmPayload = { sessionId: string, planId: string, stepId: string, stepIndex: number, kind: AiStepKind, argv: Array<string>, targetFiles: Array<string>, diff: string, snapshotPath: string, warnings: Array<string>, };
