// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai_chat_cancel` 返回值。`canceled=false` 表示该 messageId 已结束 /
 * 不存在 —— 这是良性 noop（防 race），调用方不需要处理。
 */
export type AiChatCancelResult = { canceled: boolean, };
