// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai_chat_send` 入参（v0.1）。
 */
export type AiChatSendInput = { sessionId: string, text: string, };
