// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatHistoryTurn } from "./ChatHistoryTurn";

/**
 * `ai_chat_send` 入参。
 */
export type AiChatSendInput = { sessionId: string, text: string, 
/**
 * 历史消息（按时间升序，不含本轮 `text`）。空 vec 表示首轮；前端负责
 * 滑窗截断（最近 N 轮）避免 context 溢出。
 */
history: Array<ChatHistoryTurn>, };
