// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai_context_snapshot` 入参。
 */
export type AiContextSnapshotInput = { sessionId: string, };
