// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai_context_snapshot` 返回值。
 *
 * - `pwd`：当前承载 session 初始 home_path（v0.1 不跟踪 live cwd）
 * - `recent_output`：已走 `scrubber::redact_probe_output` 硬擦策略 + 行边界对齐
 */
export type AiContextSnapshotResult = { sessionId: string, pwd: string, recentOutput: string, };
