// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";

/**
 * `ai:download_done` —— 下载流程终态（成功 / 取消 / 失败）。
 *
 * - `canceled=true` 表示用户通过 `ai_model_download_cancel` 中断；`error=None`
 * - `error=Some` 表示任意环节失败（HTTP / sha256 / 磁盘 IO）；`canceled=false`
 * - 两者都 false 表示正常完成（verify 通过，GGUF 可被下次 health check 发现）
 */
export type AiDownloadDonePayload = { canceled: boolean, error: AppError | null, };
