// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiDownloadPhase } from "./AiDownloadPhase";

/**
 * `ai:download_progress` —— 下载 / 校验 / 加载阶段进度（SPEC §5 T1.5）。
 *
 * `downloaded` / `total` 单位均为字节；`verifying` 与 `loading` 阶段没有
 * 字节级进度时 `downloaded == total` 同步发一次即可。`percent` 预计算
 * `0..=100` 整数方便 UI 直接渲染（floor 策略：59.99% → 59）。
 */
export type AiDownloadProgressPayload = { phase: AiDownloadPhase, downloaded: number, total: number, percent: number, };
