// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai:done` 的终态类别。chat / plan 共用同一事件名，但前端必须按 kind 分流。
 */
export type AiDoneKind = "chat" | "plan";
