// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai:done` —— 模型自然结束（EOG）或达到 max_tokens。
 */
export type AiDonePayload = { sessionId: string, messageId: string, 
/**
 * true 表示因 max_tokens 截断；false 表示自然结束。
 */
truncated: boolean, };
