// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiDoneKind } from "./AiDoneKind";

/**
 * `ai:done` —— 推理流结束（自然终止 / 截断 / 用户取消）。
 *
 * `truncated` 与 `canceled` 互斥：`truncated` 表示模型生成达到 max_tokens
 * 上限被截断，`canceled` 表示用户主动调用 `ai_chat_cancel` 中止；两者皆
 * 为 false 表示模型 EOG 自然结束。
 */
export type AiDonePayload = { kind: AiDoneKind, sessionId: string, messageId: string | null, planId: string | null, truncated: boolean, canceled: boolean, };
