// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模型下载进度阶段（SPEC §5 T1.5）。`fetching` 是 HTTP 字节下载；
 * `verifying` 是落盘后 sha256 校验（占时 ~30 秒）；`loading` 是
 * `LlamaRuntime::load` 把 GGUF 读入内存 + Metal buffer 初始化。
 */
export type AiDownloadPhase = "fetching" | "verifying" | "loading";
