// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";

/**
 * `ai:error` —— 推理失败 / 取消 / 任意 IPC 异常。
 */
export type AiErrorPayload = { sessionId: string, messageId: string, error: AppError, };
