// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceleratorKind } from "./AcceleratorKind";

/**
 * 健康检查输出（5 秒轮询一次，字段必须快 —— 不做 sha256 等重活）。
 */
export type AiHealthResult = { 
/**
 * llama.cpp runtime 是否已加载（模型 + backend 就绪）
 */
runtimeReady: boolean, 
/**
 * GGUF 模型文件是否存在于预期路径（只 stat，不校验哈希）
 */
modelPresent: boolean, 
/**
 * 模型名（来自 Settings.ai_model_name，例："gemma-4-E4B-it-Q4_K_M"）
 */
modelName: string, 
/**
 * 当前编译目标支持的加速器
 */
acceleratorKind: AcceleratorKind, };
