// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai_model_download_cancel` 返回值。
 */
export type AiModelDownloadCancelResult = { 
/**
 * 是否成功取消了一个正在进行的下载。false 代表没有活跃下载（race-tolerant noop）。
 */
canceled: boolean, };
