// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai_model_delete` 返回值。
 */
export type AiModelDeleteResult = { 
/**
 * 本次调用前文件是否存在（true = 实际删除；false = 本来就不在 = noop）
 */
deleted: boolean, 
/**
 * 解析出的目标路径（便于调试 / UI 展示）
 */
path: string, };
