// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 计划整体状态。v0.3a 先覆盖固定 plan 的单向生命周期；rolling revise 另行扩展。
 */
export type AiPlanStatus = "draft" | "planning" | "ready" | "running" | "awaiting_confirm" | "done" | "failed" | "canceled";
