// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiPlanStatus } from "./AiPlanStatus";
import type { AiStep } from "./AiStep";

/**
 * AI 生成的完整执行计划。
 */
export type AiPlan = { summary: string, steps: Array<AiStep>, risks: Array<string>, assumptions: Array<string>, status: AiPlanStatus, };
