// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiPlan } from "./AiPlan";

export type AiPlanRollbackResult = { plan: AiPlan, rolledBack: boolean, snapshotPath: string | null, };
