// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai:probe_queued` —— probe 因并发限制进入等待队列（T2.8）。
 *
 * UI 收到后展示"AI 队列中（第 X 位）"banner；position=0 表示已出队（清除 banner）。
 */
export type AiProbeQueuedPayload = { sessionId: string, 
/**
 * 1-based 队列位置；0 表示已出队
 */
position: number, };
