// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai:rollback_progress` —— 文件级 rollback 进度。
 */
export type AiRollbackProgressPayload = { sessionId: string, planId: string, stepId: string, currentPath: string, restoredFiles: number, totalFiles: number, snapshotPath: string, };
