// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiScrubMode } from "./AiScrubMode";

/**
 * 一次 scrub 决策的审计记录。
 */
export type AiScrubRecord = { mode: AiScrubMode, redacted: boolean, warnings: Array<string>, };
