// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai:service_state_warning` —— 文件已 rollback，但服务状态可能仍需人工确认。
 */
export type AiServiceStateWarningPayload = { sessionId: string, planId: string, stepId: string, warning: string, snapshotPath: string | null, };
