// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单步执行状态。Planner 状态机会在 T3.4 消费这些离散状态。
 */
export type AiStepStatus = "pending" | "running" | "awaiting_confirm" | "executing" | "verifying" | "done" | "failed" | "canceled" | "rolled_back";
