// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个步骤的类别。v0.2 只有 probe/write；v0.3 起补 verify；v0.3a 扩 action。
 */
export type AiStepKind = "probe" | "write" | "verify" | "action";
