// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiStepKind } from "./AiStepKind";
import type { AiStepStatus } from "./AiStepStatus";
import type { AiVerifyTemplate } from "./AiVerifyTemplate";

/**
 * 计划中的单个步骤。字段默认值保证能兼容 v0.2 的极简 JSON：
 * `{"kind":"probe","command":"..."}` / `{"kind":"write","path":"...","content":"..."}`
 */
export type AiStep = { id: string, kind: AiStepKind, status: AiStepStatus, intent: string, command: string, path: string | null, content: string | null, targetFiles: Array<string>, verifyTemplate?: AiVerifyTemplate | null, expectedObservation: string, };
