// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiStepKind } from "./AiStepKind";
import type { AiStepStatus } from "./AiStepStatus";

/**
 * `ai:step` —— 单个 plan step 的生命周期变更。
 */
export type AiStepEventPayload = { sessionId: string, planId: string, stepId: string, stepIndex: number, kind: AiStepKind, status: AiStepStatus, stdout: string | null, stderr: string | null, exitCode: number | null, message: string | null, };
