// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai:thinking` —— LLM 进入 prompt eval / planning 阶段（首 token 之前）。
 */
export type AiThinkingPayload = { sessionId: string, messageId: string, };
