// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai:token` —— 模型生成的下一个 token（可能是单字符，也可能是多字节单字）。
 */
export type AiTokenPayload = { sessionId: string, messageId: string, token: string, };
