// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 内置 verify 模板。`Custom(cmd)` 保留给 v0.3 自定义 verify 命令，但执行前仍
 * 必须再次过 allowlist。
 */
export type AiVerifyTemplate = "nginx_check" | "systemctl_is_active" | "curl_head" | { "custom": string };
