// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * 统一错误模型
 */
export type AppError = { code: ErrorCode, message: string, detail: string | null, retryable: boolean | null, };
