// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeleteFailure } from "./DeleteFailure";

/**
 * 批量删除结果
 */
export type BatchDeleteResult = { deletedCount: number, failures: Array<DeleteFailure>, };
