// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一轮历史消息。前端从 session store 切最近 N 轮（不含 current user_text）
 * 传入，后端拼进 Gemma 4 chat template。
 */
export type ChatHistoryTurn = { 
/**
 * "user" | "assistant"。使用字符串而非枚举让 ts-rs 生成 union 类型，
 * 与 `ChatMessage.role`（stores/useAiSessionStore.ts）直接对齐。
 */
role: string, content: string, };
