// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChmodFailure } from "./ChmodFailure";

/**
 * chmod 结果
 */
export type ChmodResult = { 
/**
 * 成功修改的文件数量
 */
successCount: number, 
/**
 * 失败的文件及错误信息
 */
failures: Array<ChmodFailure>, };
