// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 连接输入参数
 */
export type ConnectInput = { 
/**
 * Profile ID
 */
profileId: string, 
/**
 * 临时密码（未记住时由前端传入）
 */
password: string | null, 
/**
 * 临时 passphrase（未记住时由前端传入）
 */
passphrase: string | null, 
/**
 * 期望的服务器指纹（connect_after_trust 时用于验证）
 */
expectedFingerprint: string | null, };
