// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 递归删除进度事件
 */
export type DeleteProgress = { 
/**
 * 删除任务 ID (使用 path 作为标识)
 */
path: string, 
/**
 * 已删除的文件/目录数
 */
deletedCount: number, 
/**
 * 总文件/目录数
 */
totalCount: number, 
/**
 * 当前正在删除的路径
 */
currentPath: string, };
