// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 目录统计信息（用于删除确认对话框）
 */
export type DirectoryStats = { 
/**
 * 文件总数
 */
fileCount: number, 
/**
 * 目录总数（不含自身）
 */
dirCount: number, 
/**
 * 总大小（字节）
 */
totalSize: number, };
