// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 错误码枚举
 */
export type ErrorCode = "AUTH_FAILED" | "HOSTKEY_MISMATCH" | "TIMEOUT" | "NETWORK_LOST" | "NOT_FOUND" | "PERMISSION_DENIED" | "DIR_NOT_EMPTY" | "ALREADY_EXISTS" | "LOCAL_IO_ERROR" | "REMOTE_IO_ERROR" | "CANCELED" | "INVALID_ARGUMENT" | "UNKNOWN";
