// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 文件条目
 */
export type FileEntry = { name: string, path: string, isDir: boolean, size: number | null, 
/**
 * 修改时间 (Unix 时间戳，秒)
 */
mtime: number | null, 
/**
 * 文件权限 (Unix mode)
 */
mode: number | null, };
