// Auto-generated TypeScript bindings from Rust types via ts-rs.
// Do not edit this file manually. Re-run `pnpm generate:types` to regenerate.

// Models: profile
export type { AuthType } from "./AuthType";
export type { Profile } from "./Profile";
export type { ProfileInput } from "./ProfileInput";
export type { RecentConnection } from "./RecentConnection";

// Models: file_entry
export type { FileEntry } from "./FileEntry";
export type { SortField } from "./SortField";
export type { SortOrder } from "./SortOrder";
export type { SortSpec } from "./SortSpec";

// Models: transfer_task
export type { TransferDirection } from "./TransferDirection";
export type { TransferStatus } from "./TransferStatus";
export type { TransferTask } from "./TransferTask";
export type { TransferProgressPayload } from "./TransferProgressPayload";
export type { TransferStatusPayload } from "./TransferStatusPayload";

// Models: error
export type { ErrorCode } from "./ErrorCode";
export type { AppError } from "./AppError";

// Models: ai_plan / ai_step / ai_policy
export type { AiPlan } from "./AiPlan";
export type { AiPlanStatus } from "./AiPlanStatus";
export type { AiStep } from "./AiStep";
export type { AiStepKind } from "./AiStepKind";
export type { AiStepStatus } from "./AiStepStatus";
export type { AiVerifyTemplate } from "./AiVerifyTemplate";
export type { AiAllowlistDecision } from "./AiAllowlistDecision";
export type { AiScrubMode } from "./AiScrubMode";
export type { AiScrubRecord } from "./AiScrubRecord";

// Models: ai_events
export type { AiAwaitConfirmPayload } from "./AiAwaitConfirmPayload";
export type { AiDoneKind } from "./AiDoneKind";
export type { AiDonePayload } from "./AiDonePayload";
export type { AiErrorPayload } from "./AiErrorPayload";
export type { AiProbeQueuedPayload } from "./AiProbeQueuedPayload";
export type { AiRollbackProgressPayload } from "./AiRollbackProgressPayload";
export type { AiServiceStateWarningPayload } from "./AiServiceStateWarningPayload";
export type { AiStepEventPayload } from "./AiStepEventPayload";
export type { AiThinkingPayload } from "./AiThinkingPayload";
export type { AiTokenPayload } from "./AiTokenPayload";
export type { AiDownloadDonePayload } from "./AiDownloadDonePayload";
export type { AiDownloadPhase } from "./AiDownloadPhase";
export type { AiDownloadProgressPayload } from "./AiDownloadProgressPayload";

// Models: settings
export type { LogLevel } from "./LogLevel";
export type { Settings } from "./Settings";
export type { SettingsPatch } from "./SettingsPatch";

// Models: terminal
export type { TerminalStatus } from "./TerminalStatus";
export type { TerminalInfo } from "./TerminalInfo";
export type { TerminalOutputPayload } from "./TerminalOutputPayload";
export type { TerminalStatusPayload } from "./TerminalStatusPayload";

// Commands: session
export type { ConnectInput } from "./ConnectInput";
export type { SessionConnectResult } from "./SessionConnectResult";
export type { SessionStatusPayload } from "./SessionStatusPayload";
export type { SessionInfo } from "./SessionInfo";

// Commands: sftp
export type { DirectoryStats } from "./DirectoryStats";
export type { DeleteProgress } from "./DeleteProgress";
export type { DeleteFailure } from "./DeleteFailure";
export type { RecursiveDeleteResult } from "./RecursiveDeleteResult";
export type { ChmodResult } from "./ChmodResult";
export type { ChmodFailure } from "./ChmodFailure";

// Commands: security
export type { TrustHostKeyInput } from "./TrustHostKeyInput";

// Commands: terminal
export type { TerminalOpenInput } from "./TerminalOpenInput";
export type { TerminalInputData } from "./TerminalInputData";
export type { TerminalResizeInput } from "./TerminalResizeInput";

// Commands: ai
export type { AiChatCancelInput } from "./AiChatCancelInput";
export type { AiChatCancelResult } from "./AiChatCancelResult";
export type { AiChatSendInput } from "./AiChatSendInput";
export type { AiChatSendResult } from "./AiChatSendResult";
export type { AiContextSnapshotInput } from "./AiContextSnapshotInput";
export type { AiContextSnapshotResult } from "./AiContextSnapshotResult";
export type { AiModelDeleteResult } from "./AiModelDeleteResult";
export type { AiModelDownloadCancelResult } from "./AiModelDownloadCancelResult";
export type { AiPlanCancelInput } from "./AiPlanCancelInput";
export type { AiPlanCreateInput } from "./AiPlanCreateInput";
export type { AiPlanCreateResult } from "./AiPlanCreateResult";
export type { AiPlanRollbackInput } from "./AiPlanRollbackInput";
export type { AiPlanRollbackResult } from "./AiPlanRollbackResult";
export type { AiPlanStepConfirmInput } from "./AiPlanStepConfirmInput";
export type { AiPlanStepExecuteInput } from "./AiPlanStepExecuteInput";
export type { AiPlanStepResult } from "./AiPlanStepResult";
export type { AiHealthResult } from "./AiHealthResult";
export type { ChatHistoryTurn } from "./ChatHistoryTurn";
