// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Known Host 信息（返回给前端）
 */
export type KnownHost = { host: string, port: number, keyType: string, fingerprint: string, trustedAt: number, };
