// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthType } from "./AuthType";

/**
 * 创建/更新连接配置的输入
 */
export type ProfileInput = { id: string | null, name: string, host: string, port: number, username: string, authType: AuthType, 
/**
 * 密码 (仅用于输入，不会存储在 Profile 中)
 */
password: string | null, 
/**
 * 是否记住密码
 */
rememberPassword: boolean, 
/**
 * 私钥路径
 */
privateKeyPath: string | null, 
/**
 * passphrase (仅用于输入)
 */
passphrase: string | null, 
/**
 * 是否记住 passphrase
 */
rememberPassphrase: boolean, 
/**
 * 初始远程路径
 */
initialPath: string | null, };
