// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthType } from "./AuthType";

/**
 * 连接配置
 */
export type Profile = { id: string, name: string, host: string, port: number, username: string, authType: AuthType, 
/**
 * 密码引用 (指向系统安全存储的 key)
 */
passwordRef: string | null, 
/**
 * 私钥路径
 */
privateKeyPath: string | null, 
/**
 * passphrase 引用
 */
passphraseRef: string | null, 
/**
 * 初始远程路径
 */
initialPath: string | null, 
/**
 * 创建时间 (Unix 时间戳毫秒)
 */
createdAt: number, 
/**
 * 更新时间 (Unix 时间戳毫秒)
 */
updatedAt: number, };
