// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 文件预览结果
 */
export type ReadPreviewResult = { 
/**
 * 内容类型: "text" 或 "binary"
 */
contentType: string, 
/**
 * 文本内容（text 类型为 UTF-8 字符串，binary 类型为 None）
 */
content: string | null, 
/**
 * 实际文件大小（字节）
 */
size: number, 
/**
 * 内容是否被截断
 */
truncated: boolean, 
/**
 * 根据扩展名猜测的 MIME 类型
 */
mimeGuess: string | null, };
