// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 最近连接记录
 */
export type RecentConnection = { id: string, profileId: string, profileName: string, host: string, username: string, connectedAt: number, };
