// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeleteFailure } from "./DeleteFailure";

/**
 * 递归删除结果
 */
export type RecursiveDeleteResult = { 
/**
 * 成功删除的文件数
 */
deletedFiles: number, 
/**
 * 成功删除的目录数
 */
deletedDirs: number, 
/**
 * 删除失败的项
 */
failures: Array<DeleteFailure>, };
