// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会话信息
 */
export type SessionInfo = { sessionId: string, profileId: string, homePath: string, fingerprint: string, };
