// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会话状态事件 payload
 */
export type SessionStatusPayload = { sessionId: string, status: string, message: string | null, };
