// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 连接结果
 */
export type SessionConnectResult = { 
/**
 * 会话 ID（连接成功时返回）
 */
sessionId: string | null, 
/**
 * 远程 home 目录
 */
homePath: string | null, 
/**
 * 服务器指纹
 */
serverFingerprint: string | null, 
/**
 * 服务器密钥类型（如 ssh-ed25519, ssh-rsa）
 */
serverKeyType: string | null, 
/**
 * 是否需要确认 HostKey
 */
needHostKeyConfirm: boolean, 
/**
 * HostKey 是否为不匹配（服务器密钥已变更，非首次连接）
 */
hostKeyMismatch: boolean, };
