// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * 设置更新补丁
 */
export type SettingsPatch = { defaultDownloadDir: string | null, maxConcurrentTransfers: number | null, connectionTimeoutSecs: number | null, transferRetryCount: number | null, logLevel: LogLevel | null, terminalFontSize: number | null, terminalScrollbackLines: number | null, terminalFollowDirectory: boolean | null, };
