// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * 应用设置
 */
export type Settings = { 
/**
 * 默认下载目录
 */
defaultDownloadDir: string | null, 
/**
 * 最大并发传输数 (1-6)
 */
maxConcurrentTransfers: number, 
/**
 * 连接超时时间 (秒)
 */
connectionTimeoutSecs: number, 
/**
 * 传输失败重试次数
 */
transferRetryCount: number, 
/**
 * 日志级别
 */
logLevel: LogLevel, 
/**
 * 终端字体大小 (10-24px)
 */
terminalFontSize: number, 
/**
 * 终端 scrollback 行数 (1000-50000)
 */
terminalScrollbackLines: number, 
/**
 * 终端跟随文件浏览器目录
 */
terminalFollowDirectory: boolean, 
/**
 * AI Shell Copilot 启用开关（默认 false，off-by-default）
 */
aiEnabled: boolean, 
/**
 * AI 模型名（GGUF 文件名 stem，默认 "gemma-4-E4B-it-Q4_K_M"；与
 * `docs/approved-model-sources.md` 中 pin 的文件对齐）
 */
aiModelName: string, 
/**
 * AI 并发独立只读 probe session 上限（1-10，默认 3）
 */
maxConcurrentAiProbes: number, 
/**
 * AI 单次生成输出 token 上限（256-4096，DoS 防线）
 */
aiOutputTokenCap: number, 
/**
 * Gemma Terms of Use 接受时间戳（Unix millis UTC）。未接受即 None；
 * `ai_model_download` 未接受前返回 `AiUnavailable { detail: "license not accepted" }`。
 * SPEC §7 要求：accept 后该字段只能被用户显式重置设置清空。
 */
aiLicenseAcceptedAt: number | null, };
