// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * 应用设置
 */
export type Settings = { 
/**
 * 默认下载目录
 */
defaultDownloadDir: string | null, 
/**
 * 最大并发传输数 (1-6)
 */
maxConcurrentTransfers: number, 
/**
 * 连接超时时间 (秒)
 */
connectionTimeoutSecs: number, 
/**
 * 传输失败重试次数
 */
transferRetryCount: number, 
/**
 * 日志级别
 */
logLevel: LogLevel, 
/**
 * 终端字体大小 (10-24px)
 */
terminalFontSize: number, 
/**
 * 终端 scrollback 行数 (1000-50000)
 */
terminalScrollbackLines: number, 
/**
 * 终端跟随文件浏览器目录
 */
terminalFollowDirectory: boolean, };
