// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortField } from "./SortField";
import type { SortOrder } from "./SortOrder";

/**
 * 排序规格
 */
export type SortSpec = { field: SortField, order: SortOrder, };
