// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 终端输出事件 payload
 */
export type TerminalOutputPayload = { terminalId: string, 
/**
 * Base64 编码的输出数据
 */
data: string, };
