// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalStatus } from "./TerminalStatus";

/**
 * 终端状态事件 payload
 */
export type TerminalStatusPayload = { terminalId: string, status: TerminalStatus, message: string | null, 
/**
 * 当前重连尝试次数 (1-based)
 */
reconnectAttempt: number | null, 
/**
 * 最大重连尝试次数
 */
maxReconnectAttempts: number | null, };
