// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 终端状态
 */
export type TerminalStatus = "connected" | "disconnected" | "reconnecting" | "error";
