// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 传输进度事件 payload
 */
export type TransferProgressPayload = { taskId: string, transferred: number, total: number, speed: number, percent: number, };
