// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferDirection } from "./TransferDirection";
import type { TransferStatus } from "./TransferStatus";

/**
 * 传输任务
 */
export type TransferTask = { taskId: string, sessionId: string, direction: TransferDirection, localPath: string, remotePath: string, fileName: string, status: TransferStatus, 
/**
 * 已传输字节数
 */
transferred: number, 
/**
 * 总字节数
 */
total: number | null, 
/**
 * 传输速度 (字节/秒)
 */
speed: number | null, 
/**
 * 百分比 (0-100)
 */
percent: number | null, 
/**
 * 错误信息
 */
errorMessage: string | null, 
/**
 * 错误码
 */
errorCode: string | null, 
/**
 * 是否可重试
 */
retryable: boolean | null, 
/**
 * 创建时间 (Unix 时间戳毫秒)
 */
createdAt: number, 
/**
 * 完成时间 (Unix 时间戳毫秒)
 */
completedAt: number | null, };
