// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 传输状态
 */
export type TransferStatus = "waiting" | "running" | "success" | "failed" | "canceled";
