// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferStatus } from "./TransferStatus";

/**
 * 传输状态事件 payload
 */
export type TransferStatusPayload = { taskId: string, status: TransferStatus, errorCode: string | null, errorMessage: string | null, };
