// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 信任 HostKey 输入
 */
export type TrustHostKeyInput = { host: string, port: number, keyType: string, fingerprint: string, };
